<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bazinga_geocoder.provider.acme' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder-bundle\\ProviderFactory\\PluginProviderFactory.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder-bundle\\ProviderFactory\\ProviderFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder-bundle\\ProviderFactory\\AbstractFactory.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder-bundle\\ProviderFactory\\NominatimFactory.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder-bundle\\Plugin\\FakeIpPlugin.php';

return $this->services['bazinga_geocoder.provider.acme'] = \Bazinga\GeocoderBundle\ProviderFactory\PluginProviderFactory::createPluginProvider([0 => ${($_ = isset($this->services['Bazinga\GeocoderBundle\Plugin\FakeIpPlugin']) ? $this->services['Bazinga\GeocoderBundle\Plugin\FakeIpPlugin'] : ($this->services['Bazinga\GeocoderBundle\Plugin\FakeIpPlugin'] = new \Bazinga\GeocoderBundle\Plugin\FakeIpPlugin('127.0.0.1', '123.123.123.123'))) && false ?: '_'}, 1 => ${($_ = isset($this->services['bazinga_geocoder.provider.acme.profiler']) ? $this->services['bazinga_geocoder.provider.acme.profiler'] : ($this->services['bazinga_geocoder.provider.acme.profiler'] = new \Bazinga\GeocoderBundle\Plugin\ProfilingPlugin('acme'))) && false ?: '_'}], new \Bazinga\GeocoderBundle\ProviderFactory\NominatimFactory(), ['root_url' => 'https://nominatim.openstreetmap.org']);
