<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'httplug.stream_factory.default' shared service.

include_once $this->targetDirs[3].'\\vendor\\php-http\\discovery\\src\\StreamFactoryDiscovery.php';

return $this->services['httplug.stream_factory.default'] = \Http\Discovery\StreamFactoryDiscovery::find();
