<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Service\MapService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\MapService.php';

return $this->services['App\Service\MapService'] = new \App\Service\MapService(${($_ = isset($this->services['bazinga_geocoder.provider.acme']) ? $this->services['bazinga_geocoder.provider.acme'] : $this->load('getBazingaGeocoder_Provider_AcmeService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
