<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'property_info.reflection_extractor' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\property-info\\PropertyListExtractorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\property-info\\PropertyTypeExtractorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\property-info\\PropertyAccessExtractorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\property-info\\Extractor\\ReflectionExtractor.php';

return $this->services['property_info.reflection_extractor'] = new \Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor();
