<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Geocoder\ProviderAggregator' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Provider\\Provider.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Geocoder.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\ProviderAggregator.php';

$this->services['Geocoder\ProviderAggregator'] = $instance = new \Geocoder\ProviderAggregator();

$instance->registerProviders([0 => ${($_ = isset($this->services['bazinga_geocoder.provider.acme']) ? $this->services['bazinga_geocoder.provider.acme'] : $this->load('getBazingaGeocoder_Provider_AcmeService.php')) && false ?: '_'}]);

return $instance;
