<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.mnlk2sn' shared service.

return $this->services['service_locator.mnlk2sn'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['locationRepository' => function () {
    $f = function (\App\Repository\LocationRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\LocationRepository']) ? $this->services['App\Repository\LocationRepository'] : $this->load('getLocationRepositoryService.php')) && false ?: '_'});
}]);
