<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.kmohv7n' shared service.

return $this->services['service_locator.kmohv7n'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['mapService' => function () {
    $f = function (\App\Service\MapService $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Service\MapService']) ? $this->services['App\Service\MapService'] : $this->load('getMapServiceService.php')) && false ?: '_'});
}]);
