<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Geocoder\Dumper\Wkt' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\Dumper.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\Wkt.php';

return $this->services['Geocoder\Dumper\Wkt'] = new \Geocoder\Dumper\Wkt();
