<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['App\\Controller\\CampusController:index' => function () {
    return ${($_ = isset($this->services['service_locator.mwvtgiz']) ? $this->services['service_locator.mwvtgiz'] : $this->load('getServiceLocator_MwvtgizService.php')) && false ?: '_'};
}, 'App\\Controller\\CancelEventController:index' => function () {
    return ${($_ = isset($this->services['service_locator.8hyb8un']) ? $this->services['service_locator.8hyb8un'] : $this->load('getServiceLocator_8hyb8unService.php')) && false ?: '_'};
}, 'App\\Controller\\CityController:index' => function () {
    return ${($_ = isset($this->services['service_locator.pyphub4']) ? $this->services['service_locator.pyphub4'] : $this->load('getServiceLocator_Pyphub4Service.php')) && false ?: '_'};
}, 'App\\Controller\\EventController:edit' => function () {
    return ${($_ = isset($this->services['service_locator.gxtc6..']) ? $this->services['service_locator.gxtc6..'] : $this->load('getServiceLocator_Gxtc6__Service.php')) && false ?: '_'};
}, 'App\\Controller\\EventController:index' => function () {
    return ${($_ = isset($this->services['service_locator.1oiawak']) ? $this->services['service_locator.1oiawak'] : $this->load('getServiceLocator_1oiawakService.php')) && false ?: '_'};
}, 'App\\Controller\\EventController:new' => function () {
    return ${($_ = isset($this->services['service_locator.kmohv7n']) ? $this->services['service_locator.kmohv7n'] : $this->load('getServiceLocator_Kmohv7nService.php')) && false ?: '_'};
}, 'App\\Controller\\LocationController:index' => function () {
    return ${($_ = isset($this->services['service_locator.mnlk2sn']) ? $this->services['service_locator.mnlk2sn'] : $this->load('getServiceLocator_Mnlk2snService.php')) && false ?: '_'};
}, 'App\\Controller\\RegistrationController:register' => function () {
    return ${($_ = isset($this->services['service_locator.foocbb0']) ? $this->services['service_locator.foocbb0'] : $this->load('getServiceLocator_Foocbb0Service.php')) && false ?: '_'};
}, 'App\\Controller\\SecurityController:login' => function () {
    return ${($_ = isset($this->services['service_locator.kakbubj']) ? $this->services['service_locator.kakbubj'] : $this->load('getServiceLocator_KakbubjService.php')) && false ?: '_'};
}, 'App\\Controller\\StateController:index' => function () {
    return ${($_ = isset($this->services['service_locator.fsvj3yw']) ? $this->services['service_locator.fsvj3yw'] : $this->load('getServiceLocator_Fsvj3ywService.php')) && false ?: '_'};
}, 'App\\Controller\\UserController:index' => function () {
    return ${($_ = isset($this->services['service_locator.fgurx8j']) ? $this->services['service_locator.fgurx8j'] : $this->load('getServiceLocator_Fgurx8jService.php')) && false ?: '_'};
}, 'App\\Controller\\UserController:modifyPassword' => function () {
    return ${($_ = isset($this->services['service_locator.nwa6iz5']) ? $this->services['service_locator.nwa6iz5'] : $this->load('getServiceLocator_Nwa6iz5Service.php')) && false ?: '_'};
}, 'App\\Controller\\CampusController::index' => function () {
    return ${($_ = isset($this->services['service_locator.mwvtgiz']) ? $this->services['service_locator.mwvtgiz'] : $this->load('getServiceLocator_MwvtgizService.php')) && false ?: '_'};
}, 'App\\Controller\\CancelEventController::index' => function () {
    return ${($_ = isset($this->services['service_locator.8hyb8un']) ? $this->services['service_locator.8hyb8un'] : $this->load('getServiceLocator_8hyb8unService.php')) && false ?: '_'};
}, 'App\\Controller\\CityController::index' => function () {
    return ${($_ = isset($this->services['service_locator.pyphub4']) ? $this->services['service_locator.pyphub4'] : $this->load('getServiceLocator_Pyphub4Service.php')) && false ?: '_'};
}, 'App\\Controller\\EventController::edit' => function () {
    return ${($_ = isset($this->services['service_locator.gxtc6..']) ? $this->services['service_locator.gxtc6..'] : $this->load('getServiceLocator_Gxtc6__Service.php')) && false ?: '_'};
}, 'App\\Controller\\EventController::index' => function () {
    return ${($_ = isset($this->services['service_locator.1oiawak']) ? $this->services['service_locator.1oiawak'] : $this->load('getServiceLocator_1oiawakService.php')) && false ?: '_'};
}, 'App\\Controller\\EventController::new' => function () {
    return ${($_ = isset($this->services['service_locator.kmohv7n']) ? $this->services['service_locator.kmohv7n'] : $this->load('getServiceLocator_Kmohv7nService.php')) && false ?: '_'};
}, 'App\\Controller\\LocationController::index' => function () {
    return ${($_ = isset($this->services['service_locator.mnlk2sn']) ? $this->services['service_locator.mnlk2sn'] : $this->load('getServiceLocator_Mnlk2snService.php')) && false ?: '_'};
}, 'App\\Controller\\RegistrationController::register' => function () {
    return ${($_ = isset($this->services['service_locator.foocbb0']) ? $this->services['service_locator.foocbb0'] : $this->load('getServiceLocator_Foocbb0Service.php')) && false ?: '_'};
}, 'App\\Controller\\SecurityController::login' => function () {
    return ${($_ = isset($this->services['service_locator.kakbubj']) ? $this->services['service_locator.kakbubj'] : $this->load('getServiceLocator_KakbubjService.php')) && false ?: '_'};
}, 'App\\Controller\\StateController::index' => function () {
    return ${($_ = isset($this->services['service_locator.fsvj3yw']) ? $this->services['service_locator.fsvj3yw'] : $this->load('getServiceLocator_Fsvj3ywService.php')) && false ?: '_'};
}, 'App\\Controller\\UserController::index' => function () {
    return ${($_ = isset($this->services['service_locator.fgurx8j']) ? $this->services['service_locator.fgurx8j'] : $this->load('getServiceLocator_Fgurx8jService.php')) && false ?: '_'};
}, 'App\\Controller\\UserController::modifyPassword' => function () {
    return ${($_ = isset($this->services['service_locator.nwa6iz5']) ? $this->services['service_locator.nwa6iz5'] : $this->load('getServiceLocator_Nwa6iz5Service.php')) && false ?: '_'};
}]));
