<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Bazinga\GeocoderBundle\Plugin\FakeIpPlugin' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder-bundle\\Plugin\\FakeIpPlugin.php';

return $this->services['Bazinga\GeocoderBundle\Plugin\FakeIpPlugin'] = new \Bazinga\GeocoderBundle\Plugin\FakeIpPlugin('127.0.0.1', '123.123.123.123');
