<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Geocoder\Dumper\Gpx' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\AbstractDumper.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\Dumper.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\Gpx.php';

return $this->services['Geocoder\Dumper\Gpx'] = new \Geocoder\Dumper\Gpx();
