<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Geocoder\Dumper\GeoJson' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\AbstractArrayDumper.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\GeoJson.php';

return $this->services['Geocoder\Dumper\GeoJson'] = new \Geocoder\Dumper\GeoJson();
