<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'httplug.async_client.default' shared service.

include_once $this->targetDirs[3].'\\vendor\\php-http\\discovery\\src\\HttpAsyncClientDiscovery.php';

return $this->services['httplug.async_client.default'] = \Http\Discovery\HttpAsyncClientDiscovery::find();
