<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Geocoder\Dumper\Wkb' shared service.

include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\Dumper.php';
include_once $this->targetDirs[3].'\\vendor\\willdurand\\geocoder\\Dumper\\Wkb.php';

return $this->services['Geocoder\Dumper\Wkb'] = new \Geocoder\Dumper\Wkb();
